[project]
name = "unily-robot-mi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "지민찬", email = "mchanji727@gmail.com" }
]
requires-python = ">=3.10.1, <=3.10.12"
dependencies = [
    "mlagents",
    "mlagents-envs"
]

[tool.uv.sources]
mlagents = { path = "./lib/ml-agents", editable = true }
mlagents-envs = { path = "./lib/ml-agents-envs", editable = true }



